### ISSUE TITLE
Orders API

### ISSUE THREAD

**Issue by Chillance** [svvu/gomws#1]
Hey!

Love this initiative :)

Now, you do mention on the TODO to support more of the APIs, but since it's not clear when things will come, I thought I ask here. Right now, I'm mostly interested in the Orders API. Are you working on that right now? I'm wondering because I don't want to work on it if you already are.

Thanks!

**Comment by svvu** [comment]
Hi,
Very glad you are interested.

No, I was working on adding support to convert the response xml string to map since with raw xml, its kinda hard to use. And i was trying to convert the xml to a map of interface, and its a little complicate and find out not very useful also.

If you are interested in the orders api, i can prioritize it first, and add support to convert the response to predefined struct. I think should be able to finish it  this weekend or early next week.

If you are interested in adding the support for orders api, I appreciate it.

Thanks.

**Comment by Chillance** [comment]
Yea, if you could prioritize orders that would be very cool. I did this:

```
func (p Orders) GetOrder(orderIDList []string) *mwsHttps.Response {
    params := gmws.Parameters{
        "Action":        "GetOrder",
        "AmazonOrderId": orderIDList,
    }
    structedParams, err := params.StructureKeys("AmazonOrderId", "Id").Normalize()

    if err != nil {
        return &mwsHttps.Response{Error: err}
    }

    httpClient := p.HttpClient(structedParams)
    return httpClient.Send()
}
```

But I'm having issues with the ListOrders. So, if you would do it instead, that would be great. :)

**Comment by svvu** [comment]
Sure, I will try to finish it in the weekend

**Comment by Chillance** [comment]
Ok, super!

Regarding the other thing. So, it's just going to be a map? How about structs that matches the API?

**Comment by svvu** [comment]
i think it will be a struct to unmarshal the xml, not going to do map, since map might be hard to use, the value might be a string or an array which need to make it a map to interface.

**Comment by svvu** [comment]
i was also thinking to make it like xpath style, give it a key, return a value. But for now, i will say keep it simple, and use predefined struct which map to the api to unmarshal it.

**Comment by Chillance** [comment]
Cool, thanks! When is this going into master?

**Comment by Chillance** [comment]
Also, wouldn't it make sense to also support time.Time in Normalize? For things like ListOrders() CreatedAfter?

**Comment by svvu** [comment]
There's a few more little things to do before merge to master, should be in this week.
Yeah, i can add the type check for time, if its time, can convert to iso8601 formatted string

**Comment by Chillance** [comment]
Sweet! Thanks for quick response and solution.

Also love how fantastic Go is for things like this. :)
