### ISSUE TITLE
Convert string to time.Time ?

### ISSUE THREAD

**Issue by Chillance** [svvu/gomws#12]
Hey!

I was wondering if there are any plans of converting some strings to time.Time? For example, order.PurchaseDate.

That would make it pretty handy as I don't need to add extras so I can work with it as time. Handy also if adding the whole thing into a database.

Thanks!

**Comment by svvu** [comment]
Not really. I tried to set the type to time.Time, if the response contains valid time, it will be fine. But if the responses dont contains the time, then it will default to 0 time stamp (0001-01-01 00:00:00 +0000 UTC). This is not that bad. The only issues is the time string is not in valid time format. In that case, the whole parse process will break, and a fatal error will raise.

I can add a utility method to convert the string to time, so you can use it and dont need to write ur own method to convert it, If you think thats good

**Comment by Chillance** [comment]
Isn't that the same as time.Time{} ?

```
package main

import (
    "fmt"
    "time"
)

func main() {
    t := time.Time{}
    fmt.Printf("%+v\n", t)
}
```

Output: 0001-01-01 00:00:00 +0000 UTC

**Comment by Chillance** [comment]
Meaning, I'm not sure what the problem is. If response doesn't contain time, it could default to time.Time{}, no?

**Comment by Chillance** [comment]
Having it as a time type, will make queries to a database more supportive too, as you can do queries based on time and the database can work with it.

**Comment by svvu** [comment]
Yeah, if the response dont have time, it will default to the 0 value of Time. Thats fine, but its harder to check whether or not the response give time or not.

**Comment by svvu** [comment]
The main issues i dont use time is as i mentioned above, if the response's time is not valid format, or go dont know how to parse it, it will raise fatal error, and the process just error out, it will not return any error. I want to delegate the potential error to let the user handle instead if hard failing.

**Comment by Chillance** [comment]
Hmm, so I guess the parsing is abstracted away deeper down where it has no idea or know how to specifically deal with the time format right?

**Comment by svvu** [comment]
yeah, i think so
